### ISSUE TITLE
Issue with __init__.py 

### ISSUE THREAD

**Issue by mvela** [mbientlab/MetaWear-SDK-Python#11]
I had issues with line 74 in mbientlab/metawear/__init__.py. I think this is because
`        result[0] = RuntimeError("Could not create " + (resource if 'resource' in kwarg else "resource") ) if pointer == None else pointer
`
should be
`        result[0] = RuntimeError("Could not create " + (kwargs['resource'] if 'resource' in kwargs else "resource") ) if pointer == None else pointer
`

**Comment by scaryghost** [comment]
Yes, that line is wrong.  Thanks for pointing that out.

You should also look into why the RuntimeError is being raised in your code.

**Comment by lkasso** [comment]
Fixed in latest commit.
