### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by BakopoulouKaterina** [mbientlab/MetaWear-SDK-Python#20]
Hi! I have issues with the initialization of pointers in 'data_fuser.py ' example. I use MetaHub with the recommended Raspberry, Python 3.5.3 and Python MetaWear SDK version='1.0.2' (latest). All the other examples that not uses pointers run correctly. The examples like the data_fuser.py that use pointers and especially  functions like : 

        def processor_created(context, pointer):
            self.processor = pointer
            e.set()
            
sometimes runs correctly but some others have Segmentation Fault. Once the pointer takes value and once not.

Is there any solution for this issue? 
Thank you !!

**Comment by lkasso** [comment]
Can you please post this on our community forum. Thank you.

**Comment by sergiosierram** [comment]
I am having the same issue in Python 3.8.10 Ubuntu 20.04. I get:

error 1692107679.052502: Error on line: 296 (src/blestatemachine.cc): Operation now in progress
Connected
Services disconvered
Characteristics discovered
Descriptors found
Connected to CC:C7:39:D4:5A:62 over BLE
Configuring CC:C7:39:D4:5A:62
[1]    51059 segmentation fault (core dumped)  python3 data_fuser.py CC:C7:39:D4:5A:62
